### PR TITLE
Add azure support

### PR DESCRIPTION
**Pull request by avielb**

### CODE REVIEW

**Comment by avielb** [comment]
hey @dgzlopes 
wanted to use your project for azure, added the what's needed to check for termination in azure. 
knowledge came from here: 

1.  https://docs.microsoft.com/en-us/azure/virtual-machines/windows/scheduled-events
2. https://dev.to/omiossec/working-with-azure-vm-spot-instance-1k02

hope it will be merged soon so I can use it

**Comment by dgzlopes** [comment]
Hey @avielb, thanks a lot for the PR :) 

Do you mind removing `Azure` from the todo list? (bottom of `readme.md`)

**Comment by avielb** [comment]
@dgzlopes done

**Comment by dgzlopes** [comment]
LGTM :rocket:

**Pull request merged**
